name: androidmap
description: A map based Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  proj4dart: ^2.1.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.1
  url_strategy: ^0.2.0
  easy_splash_screen: ^1.0.4

#  cupertino_icons: ^1.0.2
#  permission_handler: ^6.0.1
#  flutter_compass: ^0.7.0


dependency_overrides:
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
#  ios: true
  image_path: "images/location.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
   - images/houshan.jpg
   - images/location.png
   - images/compass.png
   - images/plane.png
   - images/takeoff.png
   - images/arrival.png